spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/family?characterEncoding=UTF-8&serverTimezone=UTC;autoReconnect=true
    username: root
    password: 'admin'

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  flyway:
    baseline-on-migrate: true           # flyway_schema_history 테이블을 자동으로 생성할지 여부
    baseline-version: 1.0               # 최초 버전 정보
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG